CREATE TABLE Usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CI VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) UNIQUE NOT NULL,
    ROL ENUM('Cliente', 'Administrativo', 'Root') DEFAULT 'Cliente'
);

CREATE TABLE Categorias (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	AREA ENUM('Aula', 'Laboratorio', 'Taller') DEFAULT 'Aula'
)

CREATE TABLE Equipos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_IMT VARCHAR(255) UNIQUE NOT NULL,
    NUMERO_SERIE VARCHAR(255) UNIQUE,
    DIRECCION_ENLACE VARCHAR(255),
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    ID_CATEGORIA INT NOT NULL,
    UBICACION TEXT NOT NULL,
    ESTADO ENUM('Disponible', 'Ocupado', 'Mantenimiento', 'Eliminado') DEFAULT 'Disponible',
    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categorias(ID)
);

CREATE TABLE AccesoriosComponentes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_COMPONENTE VARCHAR(255) UNIQUE NOT NULL,
    NUMERO_SERIE VARCHAR(255) UNIQUE,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    ID_CATEGORIA INT NOT NULL,
    UBICACION TEXT NOT NULL,
    ESTADO ENUM('Disponible', 'Ocupado', 'Mantenimiento', 'Eliminado') DEFAULT 'Disponible',
    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categorias(ID)
);

CREATE TABLE Equipo_Componente (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EQUIPO INT NOT NULL,
    ID_COMPONENTE INT NOT NULL,
    ESTADO ENUM('Asociado', 'Eliminado') DEFAULT 'Asociado',
    FOREIGN KEY (ID_EQUIPO) REFERENCES Equipos(ID),
    FOREIGN KEY (ID_COMPONENTE) REFERENCES AccesoriosComponentes(ID)
);

CREATE TABLE Solicitudes_De_Prestamos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    FECHA_SOLICITUD DATE NOT NULL,
    FECHA_PRESTAMO_INICIO DATE NOT NULL,
    FECHA_PRESTAMO_FIN DATE NOT NULL,
    ESTADO ENUM('Pendiente', 'Aprobada', 'Rechazada') DEFAULT 'Pendiente',
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID)
);

CREATE TABLE Detalle_SolicitudPrestamo (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_SOLICITUD_PRESTAMO INT NOT NULL,
	ID_EQUIPO INT NOT NULL,
	ESTADO ENUM('Seleccionado', 'Deseleccionado') DEFAULT 'Seleccionado',
	FOREIGN KEY (ID_SOLICITUD_PRESTAMO) REFERENCES Solicitudes_De_Prestamos(ID),
	FOREIGN KEY (ID_EQUIPO) REFERENCES Equipos(ID)
);

CREATE TABLE Prestamos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_SOLICITUD INT NOT NULL,
    FECHA_DEVOLUCION DATE,
    ESTADO ENUM('Activo', 'Devuelto', 'Retrasado') DEFAULT 'Activo',
    FOREIGN KEY (ID_SOLICITUD) REFERENCES Solicitudes_De_Prestamos(ID)
);


CREATE TABLE Registros_De_Actividades (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ADMINISTRADOR INT NOT NULL,
    ID_COMPONENTE INT,
    ID_EQUIPO INT,
    ID_USUARIO INT,
    ACTIVIDAD ENUM('Crear', 'Asociar', 'Mover', 'Modificar', 'Eliminar') DEFAULT 'Crear',
    DETALLE TEXT NOT NULL,
    FECHA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ADMINISTRADOR) REFERENCES Usuarios(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID),
    FOREIGN KEY (ID_EQUIPO) REFERENCES Equipos(ID),
    FOREIGN KEY (ID_COMPONENTE) REFERENCES AccesoriosComponentes(ID)
);

CREATE TABLE Informes_Reportes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRESTAMO INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    CONTENIDO TEXT NOT NULL,
    FECHA_CREACION DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_PRESTAMO) REFERENCES Prestamos(ID)
);

// hasta este punto se crean las tablas

DELIMITER $$
CREATE TRIGGER before_usuario_insert
BEFORE INSERT
ON Usuarios
FOR EACH ROW
BEGIN
    SET NEW.CONTRASENA = SHA2(NEW.CONTRASENA, 256);
END$$
before_usuario_insert
DELIMITER;

// se crea un triger que sera el que encripte las contrasenhas de los usuarios

INSERT INTO Usuarios (CI, NOMBRE, APELLIDO, CORREO, CONTRASENA, TELEFONO, ROL)
VALUES 
('7777777', 'Root', 'Number1', 'root', 'root7!7@7#', '77777777', 'Root');

// aqui se creo el primer usuario de todos, el root