CREATE TABLE Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CI VARCHAR(10) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20) UNIQUE NOT NULL,
    ROLE ENUM('Cliente', 'Administrativo', 'Root') DEFAULT 'Cliente'
);

CREATE TABLE Categories (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    AREA ENUM('Aula', 'Laboratorio', 'Taller') DEFAULT 'Aula'
);

CREATE TABLE Equipment (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UCB_CODE VARCHAR(255) UNIQUE,
    EQUIPMENT_CODE VARCHAR(255) UNIQUE NOT NULL,
    SERIAL_NUMBER VARCHAR(255) UNIQUE,
    MANUFACTURER VARCHAR(255),
    LINK_ADDRESS VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY_ID INT NOT NULL,
    LOCATION VARCHAR(10) NOT NULL,
    EQUIPMENT_STATE ENUM('New', 'Good', 'Good - Sealed', 'Medium', 'Used') DEFAULT 'New',
    STATUS ENUM('Disponible', 'Ocupado', 'Mantenimiento', 'Eliminado') DEFAULT 'Disponible',
    FOREIGN KEY (CATEGORY_ID) REFERENCES Categories(ID)
);

CREATE TABLE ComponentsAccessories (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UCB_CODE VARCHAR(255) UNIQUE,
    COMPONENT_CODE VARCHAR(255) UNIQUE NOT NULL,
    SERIAL_NUMBER VARCHAR(255) UNIQUE,
    MANUFACTURER VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY_ID INT NOT NULL,
    LOCATION VARCHAR(10) NOT NULL,
    COMPONENT_STATE ENUM('New', 'Good', 'Good - Sealed', 'Medium', 'Used') DEFAULT 'New',
    STATUS ENUM('Disponible', 'Ocupado', 'Mantenimiento', 'Eliminado') DEFAULT 'Disponible',
    FOREIGN KEY (CATEGORY_ID) REFERENCES Categories(ID)
);

CREATE TABLE Equipment_Component (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EQUIPMENT_ID INT NOT NULL,
    COMPONENT_ID INT NOT NULL,
    STATUS ENUM('Asociado', 'Eliminado') DEFAULT 'Asociado',
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES Equipment(ID),
    FOREIGN KEY (COMPONENT_ID) REFERENCES ComponentsAccessories(ID)
);

CREATE TABLE Loan_Requests (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    REQUEST_DATE DATE NOT NULL,
    LOAN_START_DATE DATE NOT NULL,
    LOAN_END_DATE DATE NOT NULL,
    STATUS ENUM('Pendiente', 'Aprobada', 'Rechazada') DEFAULT 'Pendiente',
    FOREIGN KEY (USER_ID) REFERENCES Users(ID)
);

CREATE TABLE Loan_Request_Details (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOAN_REQUEST_ID INT NOT NULL,
    EQUIPMENT_ID INT NOT NULL,
    STATUS ENUM('Seleccionado', 'Deseleccionado') DEFAULT 'Seleccionado',
    FOREIGN KEY (LOAN_REQUEST_ID) REFERENCES Loan_Requests(ID),
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES Equipment(ID)
);

CREATE TABLE Loans (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOAN_REQUEST_ID INT NOT NULL,
    RETURN_DATE DATE,
    STATUS ENUM('Activo', 'Devuelto', 'Retrasado') DEFAULT 'Activo',
    FOREIGN KEY (LOAN_REQUEST_ID) REFERENCES Loan_Requests(ID)
);

CREATE TABLE Activity_Logs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ADMIN_ID INT NOT NULL,
    COMPONENT_ID INT,
    EQUIPMENT_ID INT,
    USER_ID INT,
    ACTIVITY ENUM('Crear', 'Asociar', 'Mover', 'Modificar', 'Eliminar') DEFAULT 'Crear',
    DETAIL TEXT NOT NULL,
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ADMIN_ID) REFERENCES Users(ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(ID),
    FOREIGN KEY (EQUIPMENT_ID) REFERENCES Equipment(ID),
    FOREIGN KEY (COMPONENT_ID) REFERENCES ComponentsAccessories(ID)
);

CREATE TABLE Reports (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    LOAN_ID INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATION_DATE DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (LOAN_ID) REFERENCES Loans(ID)
);

INSERT INTO Users (ID_CARD, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, PHONE, ROLE)
VALUES 
('12345', 'Root', 'Number2', 'roota', '12345', '12345', 'Root');

DELIMITER $$
CREATE TRIGGER before_user_insert
BEFORE INSERT
ON Users
FOR EACH ROW
BEGIN
    SET NEW.PASSWORD = SHA2(NEW.PASSWORD, 256);
END$$
before_user_insert
DELIMITER ;
