CREATE TABLE Usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CI VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20) UNIQUE NOT NULL,
    ROL ENUM('Cliente', 'Administrativo', 'Root') DEFAULT 'Cliente'
);

CREATE TABLE Categorias (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    AREA ENUM('Aula', 'Laboratorio', 'Taller') DEFAULT 'Aula'
);

CREATE TABLE Equipos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_UCB VARCHAR(255) UNIQUE,
    CODIGO_EQUIPO VARCHAR(255) NOT NULL,
    NUMERO_SERIE VARCHAR(255) UNIQUE,
    FABRICANTE VARCHAR(255),
    DIRECCION_ENLACE VARCHAR(255),
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    ID_CATEGORIA INT NOT NULL,
    UBICACION VARCHAR(255) NOT NULL,
    ESTADO_EQUIPO ENUM('Nuevo', 'Bueno', 'Bueno - Sellado', 'Regular', 'Usado') DEFAULT 'Nuevo',
    ESTADO ENUM('Disponible', 'Ocupado', 'Mantenimiento', 'Eliminado') DEFAULT 'Disponible',
    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categorias(ID)
);

CREATE TABLE ComponentesAccesorios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_UCB VARCHAR(255) UNIQUE,
    CODIGO_COMPONENTE VARCHAR(255)  NOT NULL,
    NUMERO_SERIE VARCHAR(255) UNIQUE,
    FABRICANTE VARCHAR(255),
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    ID_CATEGORIA INT NOT NULL,
    UBICACION VARCHAR(255) NOT NULL,
    ESTADO_COMPONENTE ENUM('Nuevo', 'Bueno', 'Bueno - Sellado', 'Regular', 'Usado') DEFAULT 'Nuevo',
    ESTADO ENUM('Disponible', 'Ocupado', 'Mantenimiento', 'Eliminado') DEFAULT 'Disponible',
    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categorias(ID)
);

CREATE TABLE Equipo_Componente (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EQUIPO INT NOT NULL,
    ID_COMPONENTE INT NOT NULL,
    ESTADO ENUM('Asociado', 'Eliminado') DEFAULT 'Asociado',
    FOREIGN KEY (ID_EQUIPO) REFERENCES Equipos(ID),
    FOREIGN KEY (ID_COMPONENTE) REFERENCES ComponentesAccesorios(ID)
);

CREATE TABLE SolicitudesPrestamo (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    FECHA_SOLICITUD DATE NOT NULL,
    FECHA_INICIO_PRESTAMO DATE NOT NULL,
    FECHA_FIN_PRESTAMO DATE NOT NULL,
    ESTADO ENUM('Pendiente', 'Aprobada', 'Rechazada') DEFAULT 'Pendiente',
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID)
);

CREATE TABLE DetallesSolicitudPrestamo (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_SOLICITUD_PRESTAMO INT NOT NULL,
    ID_EQUIPO INT NOT NULL,
    ESTADO ENUM('Seleccionado', 'Deseleccionado') DEFAULT 'Seleccionado',
    FOREIGN KEY (ID_SOLICITUD_PRESTAMO) REFERENCES SolicitudesPrestamo(ID),
    FOREIGN KEY (ID_EQUIPO) REFERENCES Equipos(ID)
);

CREATE TABLE Prestamos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_SOLICITUD_PRESTAMO INT NOT NULL,
    FECHA_DEVOLUCION DATE,
    ESTADO ENUM('Activo', 'Devuelto', 'Retrasado') DEFAULT 'Activo',
    FOREIGN KEY (ID_SOLICITUD_PRESTAMO) REFERENCES SolicitudesPrestamo(ID)
);

CREATE TABLE RegistrosActividades (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ADMIN INT NOT NULL,
    ID_COMPONENTE INT,
    ID_EQUIPO INT,
    ID_USUARIO INT,
    ACTIVIDAD ENUM('Crear', 'Asociar', 'Mover', 'Modificar', 'Eliminar') DEFAULT 'Crear',
    DETALLE TEXT NOT NULL,
    FECHA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ADMIN) REFERENCES Usuarios(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID),
    FOREIGN KEY (ID_EQUIPO) REFERENCES Equipos(ID),
    FOREIGN KEY (ID_COMPONENTE) REFERENCES ComponentesAccesorios(ID)
);

CREATE TABLE Reportes (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PRESTAMO INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    CONTENIDO TEXT NOT NULL,
    FECHA_CREACION DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_PRESTAMO) REFERENCES Prestamos(ID)
);

INSERT INTO Usuarios (CI, NOMBRE, APELLIDO, CORREO, CONTRASEÑA, TELEFONO, ROL)
VALUES 
('12345', 'Root', 'Numero2', 'roota', '12345', '12345', 'Root');

DELIMITER $$
CREATE TRIGGER antes_insertar_usuario
BEFORE INSERT
ON Usuarios
FOR EACH ROW
BEGIN
    SET NEW.CONTRASEÑA = SHA2(NEW.CONTRASEÑA, 256);
END$$
DELIMITER ;
